apiVersion: skaffold/v2beta10
kind: Config

build:
  artifacts:
    - image: www
      context: www

deploy:
  helm:
    releases:
      - name: www
        chartPath: charts/www
        artifactOverrides:
          image: www

profiles:
  - name: kustom-dev
    patches:
      - op: replace
        path: /deploy
        value: 
          kustomize:
            paths:
            - kustomize/overlays/dev
  - name: kustom-prod
    patches:
      - op: replace
        path: /deploy
        value: 
          kustomize:
            paths:
            - kustomize/overlays/prod