apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: www
  name: www
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
        - image: www:latest
          imagePullPolicy: Never
          name: www
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
