apiVersion: v1
kind: Service
metadata:
  labels:
    app: www
  name: www
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5001
      protocol: TCP
      targetPort: 80
  selector:
    app: www
